[package]
name = "rosebud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.2"

[dev-dependencies]
nom_assert = { path = "../nom_assert" }
